//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogEntryCategories_XREF
    {
        public int id { get; set; }
        public int entry_id { get; set; }
        public int category_id { get; set; }
    
        public virtual BlogEntry BlogEntry { get; set; }
        public virtual BlogEntryCategory BlogEntryCategory { get; set; }
    }
}
