//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogEntryCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlogEntryCategory()
        {
            this.BlogEntryCategories_XREF = new HashSet<BlogEntryCategories_XREF>();
        }
    
        public int id { get; set; }
        public string categoryname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogEntryCategories_XREF> BlogEntryCategories_XREF { get; set; }
    }
}
