//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MattMillerTimeEntities : DbContext
    {
        public MattMillerTimeEntities()
            : base("name=MattMillerTimeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlogEntry> BlogEntries { get; set; }
        public virtual DbSet<BlogEntryCategory> BlogEntryCategories { get; set; }
        public virtual DbSet<BlogEntryCategories_XREF> BlogEntryCategories_XREF { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<PicCategory> PicCategories { get; set; }
        public virtual DbSet<Pic> Pics { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
