//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fishing.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pic()
        {
            this.Comments = new HashSet<Comment>();
            this.PicCategories = new HashSet<PicCategory>();
        }
    
        public int id { get; set; }
        public string url { get; set; }
        public string thumburl { get; set; }
        public string description { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> upload_date { get; set; }
        public Nullable<bool> approved { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PicCategory> PicCategories { get; set; }
        public virtual User User { get; set; }
    }
}
